// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPu0fgXdxQpxf9_mGmxULSn62ZLfNoFYs',
    appId: '1:552749548151:web:913bae8ddd542198277c72',
    messagingSenderId: '552749548151',
    projectId: 'tiktoc-f47c6',
    authDomain: 'tiktoc-f47c6.firebaseapp.com',
    storageBucket: 'tiktoc-f47c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE__TJpkxtH0pAiMTivuTuoh63zP_wGb0',
    appId: '1:552749548151:android:a96c68c6db44a2c6277c72',
    messagingSenderId: '552749548151',
    projectId: 'tiktoc-f47c6',
    storageBucket: 'tiktoc-f47c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtd2aydv0WVRgZWAq-BadjKqRxxcZ6twk',
    appId: '1:552749548151:ios:95474c45153fa588277c72',
    messagingSenderId: '552749548151',
    projectId: 'tiktoc-f47c6',
    storageBucket: 'tiktoc-f47c6.appspot.com',
    iosClientId: '552749548151-9m78jm5orid1jfbipmvgi89lvr0llv38.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtd2aydv0WVRgZWAq-BadjKqRxxcZ6twk',
    appId: '1:552749548151:ios:ff8b03517e4a08af277c72',
    messagingSenderId: '552749548151',
    projectId: 'tiktoc-f47c6',
    storageBucket: 'tiktoc-f47c6.appspot.com',
    iosClientId: '552749548151-pmjf09l822tetdqsmt7lkvcm3mfia6mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokPractice.RunnerTests',
  );
}
